language: node_js
node_js:
  - "0.11"
before_install:
  - npm install -g grunt-cli
before_script:
  - sudo add-apt-repository ppa:juan457/zorba
  - sudo apt-get update -qq
  - sudo apt-get install zorba
script:
  - grunt test
